-- leaf & bowl 상품 DB 스키마 (PostgreSQL)
-- 1단계: 상품(메뉴·드레싱·음료)·알레르기. 주문·리뷰·관리자 계정은 2단계(docs/db-design.md 참고).
-- 실행 순서: schema.sql → seed.sql

-- 상품 종류: 메뉴(샐러드·세트), 드레싱(필수 1개 선택), 음료(추가 선택)
CREATE TYPE product_kind     AS ENUM ('menu', 'dressing', 'drink');
-- 메뉴 분류와 뱃지는 정해진 값만 허용한다 (types/product.ts 의 Category, ProductTag 와 같음)
CREATE TYPE product_category AS ENUM ('protein', 'vegan', 'new', 'other');
CREATE TYPE product_tag      AS ENUM ('BEST', 'PLANT', 'PICK', 'NEW');

-- 상품. 메뉴·드레싱·음료를 한 테이블에 두고 kind 로 구분한다.
-- id 는 화면 주소(/product/0)와 맞추기 위해 0부터 시작한다 (메뉴 0~11, 드레싱·음료는 그다음 번호).
CREATE TABLE products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
  kind         product_kind     NOT NULL DEFAULT 'menu',
  name         VARCHAR(50)      NOT NULL,
  name_en      VARCHAR(80),                                  -- 메뉴만
  description  VARCHAR(200),                                 -- 메뉴만
  price        INTEGER          NOT NULL DEFAULT 0 CHECK (price >= 0),  -- 메뉴 가격 · 음료 추가 금액 · 드레싱 0
  category     product_category,                             -- 메뉴만
  tag          product_tag,                                  -- 메뉴만, 없을 수 있음
  is_new       BOOLEAN          NOT NULL DEFAULT FALSE,
  image_url    VARCHAR(255),
  ingredients  VARCHAR(200),                                 -- 메뉴만
  kcal         INTEGER          NOT NULL CHECK (kcal >= 0),
  protein_g    INTEGER          CHECK (protein_g >= 0),      -- 메뉴만
  weight_g     INTEGER          CHECK (weight_g > 0),        -- 메뉴만
  sort_order   INTEGER          NOT NULL DEFAULT 0,          -- 같은 종류 안에서 보여줄 순서
  is_on_sale   BOOLEAN          NOT NULL DEFAULT TRUE,       -- 관리자가 판매 중지할 때 false
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),

  UNIQUE (kind, name),
  -- 메뉴는 화면에 필요한 항목이 모두 있어야 한다
  CONSTRAINT chk_menu_fields CHECK (
    kind <> 'menu' OR (
      name_en IS NOT NULL AND description IS NOT NULL AND category IS NOT NULL AND image_url IS NOT NULL
      AND ingredients IS NOT NULL AND protein_g IS NOT NULL AND weight_g IS NOT NULL
    )
  ),
  -- 드레싱·음료에는 메뉴 전용 분류·뱃지를 쓰지 않는다
  CONSTRAINT chk_option_fields CHECK (kind = 'menu' OR (category IS NULL AND tag IS NULL AND is_new = FALSE)),
  -- 드레싱은 무료
  CONSTRAINT chk_dressing_free CHECK (kind <> 'dressing' OR price = 0)
);
CREATE INDEX idx_products_kind_category ON products (kind, category);

-- 알레르기 유발 재료 (닭고기, 우유, 토마토 …). 이름은 중복 불가.
CREATE TABLE allergens (
  id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name  VARCHAR(20) NOT NULL UNIQUE
);

-- 상품(메뉴·드레싱) ↔ 알레르기 (N:M)
CREATE TABLE product_allergens (
  product_id   INTEGER NOT NULL REFERENCES products (id)  ON DELETE CASCADE,
  allergen_id  INTEGER NOT NULL REFERENCES allergens (id) ON DELETE RESTRICT,
  PRIMARY KEY (product_id, allergen_id)
);
