-- leaf & bowl 상품 DB 스키마 (PostgreSQL)
-- 1단계: 상품·드레싱·음료·알레르기. 주문·리뷰·관리자 계정은 2단계(docs/db-design.md 참고).
-- 실행 순서: schema.sql → seed.sql

-- 상품 분류와 뱃지는 정해진 값만 허용한다 (types/product.ts 의 Category, ProductTag 와 같음)
CREATE TYPE product_category AS ENUM ('protein', 'vegan', 'new', 'other');
CREATE TYPE product_tag      AS ENUM ('BEST', 'PLANT', 'PICK', 'NEW');

-- 상품. id 는 화면 주소(/product/0)와 맞추기 위해 0부터 시작한다.
CREATE TABLE products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
  name         VARCHAR(50)      NOT NULL,
  name_en      VARCHAR(80)      NOT NULL,
  description  VARCHAR(200)     NOT NULL,
  price        INTEGER          NOT NULL CHECK (price >= 0),
  category     product_category NOT NULL,
  tag          product_tag,
  is_new       BOOLEAN          NOT NULL DEFAULT FALSE,
  image_url    VARCHAR(255)     NOT NULL,
  ingredients  VARCHAR(200)     NOT NULL,
  kcal         INTEGER          NOT NULL CHECK (kcal >= 0),
  protein_g    INTEGER          NOT NULL CHECK (protein_g >= 0),
  weight_g     INTEGER          NOT NULL CHECK (weight_g > 0),
  is_on_sale   BOOLEAN          NOT NULL DEFAULT TRUE,   -- 관리자가 판매 중지할 때 false
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ      NOT NULL DEFAULT now()
);
CREATE INDEX idx_products_category ON products (category);

-- 알레르기 유발 재료 (닭고기, 우유, 토마토 …). 이름은 중복 불가.
CREATE TABLE allergens (
  id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name  VARCHAR(20) NOT NULL UNIQUE
);

-- 상품 ↔ 알레르기 (N:M)
CREATE TABLE product_allergens (
  product_id   INTEGER NOT NULL REFERENCES products (id)  ON DELETE CASCADE,
  allergen_id  INTEGER NOT NULL REFERENCES allergens (id) ON DELETE RESTRICT,
  PRIMARY KEY (product_id, allergen_id)
);

-- 드레싱 (필수 1개 선택). 가격은 무료라 컬럼 없음.
CREATE TABLE dressings (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
  name        VARCHAR(30)  NOT NULL UNIQUE,
  kcal        INTEGER      NOT NULL CHECK (kcal >= 0),
  image_url   VARCHAR(255),
  sort_order  INTEGER      NOT NULL DEFAULT 0
);

-- 드레싱 ↔ 알레르기 (N:M)
CREATE TABLE dressing_allergens (
  dressing_id  INTEGER NOT NULL REFERENCES dressings (id) ON DELETE CASCADE,
  allergen_id  INTEGER NOT NULL REFERENCES allergens (id) ON DELETE RESTRICT,
  PRIMARY KEY (dressing_id, allergen_id)
);

-- 추가 음료 (선택, 여러 개 가능)
CREATE TABLE drinks (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
  name        VARCHAR(30)  NOT NULL UNIQUE,
  price       INTEGER      NOT NULL CHECK (price >= 0),   -- 추가 금액 (원)
  kcal        INTEGER      NOT NULL CHECK (kcal >= 0),
  image_url   VARCHAR(255),
  sort_order  INTEGER      NOT NULL DEFAULT 0
);
