-- leaf & bowl 상품 DB 스키마 (PostgreSQL)
-- 1단계: 상품(메뉴·드레싱·음료)·알레르기. 주문·리뷰·관리자 계정은 2단계(docs/db-design.md 참고).
-- 실행 순서: schema.sql → seed.sql

-- 상품 분류. 메뉴는 protein·vegan·new·other, 옵션은 dressing·drink 로 구분한다.
CREATE TYPE product_category AS ENUM ('protein', 'vegan', 'new', 'other', 'dressing', 'drink');
CREATE TYPE product_tag      AS ENUM ('BEST', 'PLANT', 'PICK', 'NEW');

-- 상품. 메뉴·드레싱·음료를 한 테이블에 두고 category 로 구분한다.
-- id 는 화면 주소(/product/0)와 맞추기 위해 0부터 시작한다 (메뉴 0~11, 드레싱 12~16, 음료 17~20).
CREATE TABLE products (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 START WITH 0) PRIMARY KEY,
  name         VARCHAR(50)      NOT NULL UNIQUE,
  name_en      VARCHAR(80)      NOT NULL,
  description  VARCHAR(200)     NOT NULL,
  price        INTEGER          NOT NULL CHECK (price >= 0),      -- 메뉴 가격 · 음료 추가 금액 · 드레싱 0
  category     product_category NOT NULL,
  tag          product_tag,                                       -- 뱃지. 없는 상품이 많아 비워 둘 수 있다
  is_new       BOOLEAN          NOT NULL DEFAULT FALSE,
  image_url    VARCHAR(255)     NOT NULL,
  ingredients  VARCHAR(200)     NOT NULL,                         -- 주요 재료·성분, " · " 로 구분
  kcal         INTEGER          NOT NULL CHECK (kcal >= 0),
  protein_g    INTEGER          NOT NULL CHECK (protein_g >= 0),
  weight_g     INTEGER          NOT NULL CHECK (weight_g >= 0),   -- 1회분 중량 (음료는 ml ≒ g)
  sort_order   INTEGER          NOT NULL DEFAULT 0,               -- 같은 분류 안에서 보여줄 순서
  is_on_sale   BOOLEAN          NOT NULL DEFAULT TRUE,            -- 관리자가 판매 중지할 때 false
  created_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),

  -- 드레싱·음료에는 메뉴 전용 뱃지·신메뉴 표시를 쓰지 않는다
  CONSTRAINT chk_option_no_badge CHECK (category NOT IN ('dressing', 'drink') OR (tag IS NULL AND is_new = FALSE)),
  -- 드레싱은 무료
  CONSTRAINT chk_dressing_free   CHECK (category <> 'dressing' OR price = 0)
);
CREATE INDEX idx_products_category ON products (category);

-- 알레르기 유발 재료 (닭고기, 우유, 토마토 …). 이름은 중복 불가.
CREATE TABLE allergens (
  id    INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name  VARCHAR(20) NOT NULL UNIQUE
);

-- 상품 ↔ 알레르기 (N:M)
CREATE TABLE product_allergens (
  product_id   INTEGER NOT NULL REFERENCES products (id)  ON DELETE CASCADE,
  allergen_id  INTEGER NOT NULL REFERENCES allergens (id) ON DELETE RESTRICT,
  PRIMARY KEY (product_id, allergen_id)
);
